sheets:
  orders_spreadsheet_id: 17x0SVsHU73z6cpshrTtGiXi9X1NfBXnjAUCw6Y0C8H4
  abandoned_spreadsheet_id: 1dtHUylkMcsLb_T6QWCVVoT0a8IcLNMI3AtVtMya_Vb8
  report_sheet_name: Stakeholder Report
files:
  master_csv: master_report_20250401_to_20250502.csv
stakeholders:
- name: Deepasha
  limit: 130
- name: Khushi
  limit: 130
- name: Komal
  limit: 130
