sheets:
  orders_spreadsheet_id: 17x0SVsHU73z6cpshrTtGiXi9X1NfBXnjAUCw6Y0C8H4
  abandoned_spreadsheet_id: 14ZnB0AtEzbeDidHWL1mULPnsWaN6EtPu-qhdirKb2SM
  report_sheet_name: Stakeholder Report
files:
  master_csv: shopify_report_20250401_to_20250430.csv
stakeholders:
- name: Deepasha
  limit: 102
- name: Khushi
  limit: 100
- name: Komal
  limit: 100
