sheets:
  orders_spreadsheet_id: 1V8FjDdfWnh3sLDQA5TpV_S2UOT5AuRyyadMtgpfm_Ec
  abandoned_spreadsheet_id: 1wu1zI4mBfDmY5eWgnZKCg5g4UzIutyuY2DIk-enygC4
  report_sheet_name: Stakeholder Report
files:
  master_csv: master_report_20250401_to_20250502.csv
stakeholders:
- name: Deepasha
  limit: 130
- name: Khushi
  limit: 130
- name: Komal
  limit: 130
